# Generated by Django 2.2 on 2019-04-23 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Designation',
                'verbose_name_plural': 'Designations',
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_firstname', models.CharField(max_length=255)),
                ('employee_lastname', models.CharField(max_length=255)),
                ('employee_username', models.CharField(max_length=255)),
                ('employee_password', models.CharField(max_length=255)),
                ('employee_email', models.EmailField(max_length=255, unique=True)),
                ('employee_birth_date', models.DateField()),
                ('employee_joining_date', models.DateField()),
                ('employee_salary', models.IntegerField()),
                ('employee_leaves', models.IntegerField()),
                ('employee_photo', models.FileField(upload_to='')),
                ('employee_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Branch')),
                ('employee_designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.Designation')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
    ]
