# Generated by Django 2.2 on 2019-04-23 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_auto_20190423_1758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='joiningdate',
            new_name='joining date',
        ),
    ]
