# Generated by Django 2.2 on 2019-04-24 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0004_auto_20190423_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='username',
        ),
        migrations.AddField(
            model_name='employees',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employees',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
