# Generated by Django 2.2 on 2019-04-24 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_auto_20190424_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='password',
        ),
    ]
