# Generated by Django 2.2 on 2019-04-24 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_remove_employees_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='email',
        ),
    ]
