# Generated by Django 2.2 on 2019-04-25 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('employees', '0012_auto_20190424_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.AddField(
            model_name='profile',
            name='branch',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='company.Branch'),
        ),
        migrations.AddField(
            model_name='profile',
            name='designation',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='employees.Designation'),
        ),
        migrations.AddField(
            model_name='profile',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='leaves',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='salary',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
