# Generated by Django 2.2 on 2019-04-25 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_auto_20190425_0209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
    ]
