# Generated by Django 2.2 on 2019-05-01 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0016_auto_20190425_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('client_email', models.CharField(max_length=255)),
                ('client_phone', models.IntegerField()),
                ('client_address', models.TextField(max_length=255)),
                ('client_city', models.CharField(max_length=255)),
                ('client_state', models.CharField(max_length=255)),
                ('client_zipcode', models.CharField(max_length=255)),
                ('client_country', models.CharField(max_length=255)),
                ('client_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
    ]
