# Generated by Django 2.2 on 2019-05-01 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0017_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='client_active',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='client_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='client_city',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='client_country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='client_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='client_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='client_phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='client_state',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='client_zipcode',
            new_name='zipcode',
        ),
    ]
