# Generated by Django 2.2 on 2019-05-10 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0019_auto_20190509_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access', models.CharField(max_length=255)),
                ('employee_designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.Designation')),
            ],
            options={
                'verbose_name': 'Employee Access',
                'verbose_name_plural': 'Employee Access',
            },
        ),
    ]
