# Generated by Django 2.2 on 2019-05-16 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0021_interview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN PROGRESS', 'In Progress'), ('TAKEN', 'Taken'), ('REJECTED', 'Rejected'), ('SELECTED', 'Selected')], default='SCHEDULED', max_length=255),
        ),
        migrations.CreateModel(
            name='Knowledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1000)),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('sourcecode_file', models.FileField(blank=True, null=True, upload_to='')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.Technology')),
            ],
            options={
                'verbose_name': 'Knowledge Entry',
                'verbose_name_plural': 'Knowledge Entry',
            },
        ),
    ]
