# Generated by Django 2.2 on 2019-05-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0022_auto_20190516_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Performance Question',
                'verbose_name_plural': 'Performance Questions',
            },
        ),
    ]
